# Generated by Django 6.0.2 on 2026-02-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Absent'), (1, 'Present')], help_text='Employee attendance status.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='employee.employee', verbose_name='employee')),
            ],
        ),
    ]
