# Generated by Django 6.0.2 on 2026-03-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified at'),
        ),
        migrations.RunSQL(
            "UPDATE employee_attendance SET updated_at = created_at;"
        ),
    ]
